### ISSUE TITLE
add possibility to select additional data from the asset objects as meta data for the new asset field & to add userdefined meta data fields

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#549]
**The feature would affect:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**Is your feature request related to a problem? Please describe.**
At the moment it is possible to set the alt text, title/caption and copyright. For some cases users need additional fields to accomodate other use-cases for example when creating a gallery where the creation date is needed and the author in an extra field.

**Describe the solution you'd like**
It would be a very helpful addition to be able to select additional information from the asset object https://www.storyblok.com/docs/api/management#core-resources/assets/the-asset-object to be added to the asset field when choosing an asset from the asset manager.

**Comment by alvarosabu** [comment]
Hi @Slackman2015, we are closing this issue because this repository was used in the early days for support-related questions, but we've since transitioned to more effective channels for helping our users.

Please, refer to the following resources:

Storyblok Github Org: https://github.com/storyblok
Storyblok Docs: https://www.storyblok.com/docs
Official Support: https://support.storyblok.com
Join our Discord: https://www.storyblok.com/join-discord

Thanks for the understanding 🙏🏻
